# Attention! Do not change this value if you do not want your config to be deleted!
config-version: 1

# You can block blocks that you don't want the player to be able to teleport to.
# Use literal block ID without "minecraft:"
BlockTPBlock:
  - LAVA
  - BEDROCK

# You can change the teleportation range using X, Y, Z coordinates:
x: 10
y: 0 #Attention! Don't change this value if you don't want players to spawn in the air.
z: 10

# Setting the Title that the player will see before teleporting.
Title:
  Enabled: true # Set to false if you want to disable Title.
  HadeIn: 10
  FadeOut: 10
  MainTitle: '&6&lTeleport'
  SubTitle: '&fPlease wait'
  DelayTP: 3

Scrolls:
  # Gives the ability to teleport to a random point in the world in which the player is located.
  RandomTP:
    Enabled: true
    Permission: 'example.permission'
    ItemIA: ''
    Activate:
      RIGHT_CLICK: true
      LEFT_CLICK: true
  # Gives the ability to teleport a specific item to a house set by the player. Uses the Essentials hook.
  HomeTP:
    Enabled: true
    Permission: 'example.permission'
    ItemIA: ''
    Activate:
      RIGHT_CLICK: true
      LEFT_CLICK: true
  # Gives the ability to teleport to pre-prepared points. To install a checkpoint, use: /stp checkpoint add
  # Permission: stp.checkpoint.add
  CheckpointTP:
    Enabled: true
    Permission: 'example.permission'
    ItemIA: ''
    Activate:
      RIGHT_CLICK: true
      LEFT_CLICK: true

# Activate debug only if you need to report to the developer, or if something doesn't work for you.
Debug:
  RandomTP:
   Enabled: true
   Console: true
   Message: true # Permission: stp.admin.debug or stp.*
  HomeTP:
   Enabled: true
   Console: true
   Message: true # Permission: stp.admin.debug or stp.*
  CheckpointTP:
    Enabled: true
    Console: true
    Message: true # Permission: stp.admin.debug or stp.*
  All:
    Enabled: true
    Console: true
    Message: true # Permission: stp.admin.debug or stp.*